import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <header className="header">
          <Link href="/hierarchy">Иерархия</Link>
          <Link href="/">Должности</Link>
          <Link href="/staffList">Список персонала</Link>
          <Link href="/equipmentSets">Наборы экипировки</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
