import { Inter } from "next/font/google";
import "./globals.scss";
import Link from "next/link";
import styles from "./header.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <header className={styles.header}>
          <Link href="/hierarchy" className={styles.navLink}>
            Иерархия
          </Link>
          <Link href="/" className={styles.navLink}>
            Должности
          </Link>
          <Link href="/staffList" className={styles.navLink}>
            Список персонала
          </Link>
          <Link href="/equipmentSets" className={styles.navLink}>
            Наборы экипировки
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
